In [1]:
# pip install pandas

In [2]:
import os 
import numpy as np 
import pandas as pd

In [3]:
df =pd.read_csv(r"C:\Users\kumaw\OneDrive\Desktop\Data Science\Pandas\Used_Bikes.csv")

In [4]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [5]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [6]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [7]:
df.tail(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32635,Suzuki Zeus 125cc,35000.0,Ahmedabad,11885.0,First Owner,12.0,125.0,Suzuki
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [9]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [10]:
df['brand']

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: object

In [11]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [12]:
df[["brand","price"]]

               brand     price
0                TVS   35000.0
1      Royal Enfield  119900.0
2            Triumph  600000.0
3                TVS   65000.0
4             Yamaha   80000.0
...              ...       ...
32643           Hero   39000.0
32644            TVS   30000.0
32645          Bajaj   60000.0
32646           Hero   15600.0
32647          Bajaj   22000.0

[32648 rows x 2 columns]

In [13]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [14]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [15]:
df['city'].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',
       'Bikaner', 'Malout', 'Jammu', 'Rajnandgaon', 'Unnao', 'Godhara',
       'Kolhapur', 'Satara', 'Siwan', 'Dadra & Nagar Haveli', 'Bhiwani',
       'Koppal', 'Nizamabad', 'Madurai', 'Ujjain', 'Palakkad',
       'Tiruvallur', 'Panchkula', 'Nanjangud', 'Jhansi', 'Sonipat',
       'Puttur', 'Hoshiarpur', 'Gohana', 'Gautam Buddha Nagar',
       'Durgapur', 'Palwal', 'Chatrapur', 'Howrah', 'Jind', 'Hubli',
       'Panipat', 'Bharatpur', 'Vellore', 'Ambala', 'Guwahati', 'Gangtok',
       'Rajahmundry', 'Tiruchirappalli', 'Belgaum', 'Balaghat', 'Jatani',
       'Asansol', 'Bilaspur', 'Thanjavur', 'Raigarh(mh)', 'Mandi Dabwali',
       'Basti', 'Bolpur', 'Aligarh', 'Balrampur', 'Ratnagiri', 'Muktsar',
       'Baran', 'Haldwani', 'Thiruvananthapuram', 'Indore', 'Buxar',
       'Chaksu', 'Haridwar', 'Bharuch', 'Muvattupuzha', 'Patna',
       'Simdega', 'Singhbhum', 'Bardhaman', 'Pathankot', 'Kharar',
       'Silchar', 'Jhalawar', 'Roorkee', 'Saharanpur', 'Solapur',
       'Gwalior', 'Alibag', 'Katni', 'Khedbrahma', 'Valsad', 'Satna',
       'Hooghly', 'Gurdaspur', 'Dadri', 'Amravati', 'Durg', 'Mehsana',
       'Lansdowne', 'Cuttack', 'Jaisalmer', 'Hanumangarh', 'Dungarpur',
       'Sri Ganganagar', 'Margao', 'Chinsurah', 'Bhatinda', 'Sibsagar',
       'Khalilabad', 'Dehradun', 'Anand', 'Sambalpur', 'Ankleshwar',
       'Purnia', 'Tiruverkadu', 'Bahadurgarh', 'Udaipur', 'Jodhpur',
       'Sheikhpura', 'Pondicherry', 'Sirsa', 'Godavari', 'Ajmer',
       'Moradabad', 'Raipur', 'Navsari', 'Herbertpur', 'Jamshedpur',
       'Ramanagar', 'Berhampur', 'Vijayawada', 'Murad Nagar',
       'Chandrapur', 'Jamtara', 'Uppidamangalam', 'Nalagarh', 'Una',
       'Chakan', 'Idukki', 'Shivpuri', 'Arkalgud', 'Bidar', 'Rupnagar',
       'Deoghar', 'Kanchipuram', 'Vapi', 'Medak', 'Kasargode', 'Dhanbad',
       'Dakshina Kannada', 'Ganaur', 'Jamalpur', 'Amraoti', 'Mangalore',
       'Deolali', 'Gandhinagar', 'Chitradurga', 'Chinchwad', 'Jhajjar',
       'Jagdalpur', 'Ranoli', 'Raiwala', 'Guntur', 'Badarpur', 'Adalaj',
       'Alipore', 'Bhawani Mandi', 'Mughalsarai', 'Kollam', 'Farukhabad',
       'Thiruvallur', 'Udaipurwati', 'Rasra', 'Latur', 'Krishna',
       'Gangaikondan', 'Warangal', 'Uluberia', 'Poonamallee', 'Nagaon',
       'Hissar', 'Kanyakumari', 'Morbi', 'Bankura', 'Virar', 'Tikamgarh',
       'Sultanpur', 'Tirunelveli', 'Bihar Shariff', 'Goa-panaji',
       'Ganganagar', 'Kolar', 'Bahadurpur', 'Batala', 'Budhlada',
       'Muzaffarnagar', 'Adyar', 'Calicut', 'Raigarh', 'Sonepat',
       'Chikkaballapur', 'Kasba', 'Bulandshahr', 'Burdwan', 'Anjar',
       'Marandahalli', 'Badaun', 'Namakkal', 'Puri', 'Alwar',
       'Surendranagar', 'Khandela', 'Kullu', 'Mohammadabad', 'Sangareddy',
       'Ghazipur', 'Shimla', 'Azamgarh', 'Chenani', 'Kanpur Nagar',
       'Trivandrum', 'Secunderabad', 'Kurukshetra', 'Dhariawad',
       'Bargarh', 'Gadarpur', 'Chikamaglur', 'Karim Nagar', 'Kotdwar',
       'Jalaun', 'Parola', 'Bareilly', 'Salem', 'Indi', 'Muzaffarpur',
       'Nayagarh', 'Jalgaon', 'Ambikapur', 'Udupi', 'Junagadh',
       'Dibrugarh', 'Faridkot', 'Naraingarh', 'Karwar',
       'Sant Kabir Nagar', 'Viramgam', 'Manali', 'Gadwal', 'Honavar',
       'Mathura', 'Khandwa', 'Solan', 'Sitapur', 'Betul', 'Anantapur',
       'Sholapur', 'Pinjore', 'Qadian', 'Sangrur', 'Jorhat', 'Palanpur',
       'Narnaul', 'Palamu', 'Falakata', 'Ferozepur', 'Porbandar',
       'Dwarka', 'Rangpo', 'Cannanore (kannur)', 'Churu', 'Baghpat',
       'Jhumri Tilaiya', 'Naihati', 'Virudhunagar', 'Dharmavaram',
       'Darbhanga', 'Nawanshahr', 'Sangli', 'Suri', 'Yamuna Nagar',
       'Vasai', 'Aluva', 'Sirsi', 'Bijapur', 'Krishnagar', 'Bhiwadi',
       'Bellary', 'Erode', 'Aquem', 'Nellore', 'Udhampur', 'Dhamtari',
       'Vandalur', 'Motihari', 'Dharwar', 'Shimoga', 'Jhunjhunu',
       'Bijnor', 'Yemmiganur', 'Bokaro', 'Kurnool', 'Srinagar', 'Ranip',
       'Davanagere', 'Rajouri', 'Begusarai', 'Goregaon', 'Bally',
       'Kachchh', 'Nagaur', 'Anekal', 'Mansa', 'Nanded', 'Dharamasala',
       'Chhindwara', 'Jamnagar', 'Zirakpur', 'Abohar', 'Barabanki',
       'Nabha', 'Kadapa', 'Perumbavoor', 'Sundargarh', 'Nazira',
       'Pratapgarh', 'Dharmapuri', 'Thangadh', 'Lonavala', 'Vizianagaram',
       'Kathua', 'Deesa', 'Tiruppur', 'Gadchiroli', 'Gangaghat', 'Bhuj',
       'Vastral', 'Phagwara', 'Kheda', 'Swaimadhopur', 'Kharagpur',
       'Jobner', 'Gondia', 'Bundi', 'Hamirpur', 'Dongargaon',
       'Mubarakpur', 'Tumkur', 'Sanand', 'Kartarpur', 'Bhavnagar',
       'Farrukhabad', 'Kadi', 'Seppa', 'Challakere', 'Dhubri', 'Deoria',
       'Akot', 'Alappuzha', 'Bhiwandi', 'Shillong', 'Osmanabad', 'Kendua',
       'Uran', 'Jaunpur', 'Hisar', 'Bodhan', 'Bhubaneswar', 'Raiganj',
       'Bhilai Nagar', 'Baloda', 'Anantnag', 'Berhampore', 'Silvasa',
       'Hospet', 'Palai', 'Sidhi'], dtype=object)

In [16]:
df['brand'].nunique()

23

In [17]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [18]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [19]:
df.duplicated().sum()

25324

In [20]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [21]:
df.duplicated().sum()

25324

In [22]:
df.drop_duplicates(inplace=True)

In [23]:
df.duplicated().sum()

0

In [24]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [25]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [26]:
# df.dropna(inplace=True)

# y = mx+c  linear regreesion 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   object
 1   price       7324 non-null   float64
 2   city        7324 non-null   object
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   object
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   object
dtypes: float64(4), object(4)
memory usage: 515.0+ KB

In [27]:
# y = mx+c 
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [28]:
owner_dict = {
    'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
}

In [29]:
# df['owner']=df['owner'].map(owner_dict)

In [30]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [31]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   object
 1   price       7324 non-null   float64
 2   city        7324 non-null   object
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   object
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   object
dtypes: float64(4), object(4)
memory usage: 515.0+ KB

In [33]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [34]:
# df.drop('city', axis=1,inplace=True)

In [35]:
# df.drop(['city', 'bike_name'], axis=1 , inplace=True)

In [36]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [37]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}
# df['brand']=df['brand'].map(brand_dict)

In [38]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   object
 1   price       7324 non-null   float64
 2   city        7324 non-null   object
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   object
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   object
dtypes: float64(4), object(4)
memory usage: 515.0+ KB

In [40]:
obj_val =df.select_dtypes(include='O')

In [41]:
obj_val

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [42]:
num_val =df.select_dtypes(exclude='O')

In [43]:
num_val

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [44]:
complete_Data =pd.concat([obj_val, num_val], axis=1)

In [45]:
complete_Data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000.0,7127.0,5.0,220.0

In [46]:
tvs_brand =df[df['brand']=='TVS']

In [47]:
tvs_brand['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner'], dtype=object)

In [48]:
# brand = " royal", km = >50Km, owner = 1st, age 2 sal se km

In [49]:
tvs_first =tvs_brand[tvs_brand['owner']=='First Owner']

In [50]:
tvs_first[tvs_first['age']<=2]

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [52]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
tvvs_brand=df[df['brand']=='TVS']

In [57]:
tvs_under2 =tvs_brand[tvvs_brand['age']<=2]

In [63]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) ]

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [58]:
tvs_under2[tvs_under2['kms_driven']<=20000]

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [64]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [65]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [68]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [73]:
# df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<150000) ]
df.query("brand=='Royal Enfield' and age <=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [76]:
df.drop(['bike_name', 'city'], axis=1, inplace=True)

In [82]:
df.duplicated().sum()

18

In [83]:
df.drop_duplicates(inplace=True)

In [85]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
# df.dropna(inplace=True)

In [78]:
x =df.drop('price', axis=1)

In [79]:
y =df[['price']]

In [80]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [81]:
x  ##### y = mx+c

      kms_driven        owner  age  power            brand
0        17654.0  First Owner  3.0  110.0              TVS
1        11000.0  First Owner  4.0  350.0    Royal Enfield
2          110.0  First Owner  8.0  675.0          Triumph
3        16329.0  First Owner  4.0  180.0              TVS
4        10000.0  First Owner  3.0  150.0           Yamaha
...          ...          ...  ...    ...              ...
9362     48587.0  First Owner  8.0  150.0             Hero
9369     60000.0  First Owner  9.0  220.0            Bajaj
9370      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371     21300.0  First Owner  4.0  400.0            Bajaj
9372      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 5 columns]

In [ ]:
# from sklern

In [86]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [87]:
df.to_csv("clean_bike_data.csv")